# load("@rules_proto_grpc//cpp:defs.bzl", "cpp_grpc_library")

grpc_library(
    name = "query_service_proto",
    srcs = ["query_service.proto"],
    visibility = ["PUBLIC"],
)

#cpp_grpc_library(
#    name = "cpp_query_service_proto",
#    protos = [
#        ":query_service_proto",
#    ],
#    visibility = ["//visibility:public"],
# )
# proto_language(
