cc_binary(
    name = "regexdb",
    srcs = [
        "main.cc",
        "query_service.cc",
        "query_service.h",
    ],
    deps = [
        "//librereuse:rereuse",
        "//proto:cpp_query_service_proto",
    ],
)
